import type {
  ActivityTimeline,
  DashboardSummary,
  Finding,
  FindingListResponse,
  KevSummary,
  WorkspaceData,
} from "@/lib/api";

const now = new Date("2026-05-15T12:00:00.000Z").toISOString();

export const demoFindings: Finding[] = [
  {
    id: "kev-cve-2024-3094",
    title: "CVE-2024-3094 XZ Utils supply-chain backdoor exposure",
    description: "Source dataset: CISA KEV\nCVE: CVE-2024-3094\nVendor/Project: XZ Utils\nProduct: liblzma\nVulnerability: Supply-chain backdoor in compression library\nDue date: 2026-05-10\nKnown ransomware use: Known",
    source: "cisa_kev",
    severity: "critical",
    status: "new",
    category: "supply_chain",
    affected_asset: "linux-build-fleet",
    reporter: "cisa-kev-import",
    confidence: 0.96,
    created_at: now,
    updated_at: now,
  },
  {
    id: "bb-idor-invoices",
    title: "IDOR in invoice retrieval exposes tenant billing records",
    description: "Changing invoice_id in /v1/invoices/{invoice_id} returns another customer's invoice data.",
    source: "bug_bounty",
    severity: "high",
    status: "triaged",
    category: "idor",
    affected_asset: "/v1/invoices/{invoice_id}",
    reporter: "security-researcher",
    confidence: 0.91,
    created_at: now,
    updated_at: now,
  },
  {
    id: "secret-github-api-key",
    title: "Exposed API key in public GitHub repository",
    description: "A secret scanning alert detected an active API key committed to a public repository.",
    source: "secret_scan",
    severity: "high",
    status: "in_remediation",
    category: "exposed_secret",
    affected_asset: "github/example-repo",
    reporter: "secret-scanner",
    confidence: 0.88,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cloud-public-bucket",
    title: "Public object storage bucket with customer exports",
    description: "Cloud posture scan found public read access on an object storage bucket containing export artifacts.",
    source: "cloud_alert",
    severity: "medium",
    status: "needs_human_review",
    category: "cloud_misconfiguration",
    affected_asset: "s3://customer-export-artifacts",
    reporter: "cloud-cspm",
    confidence: 0.73,
    created_at: now,
    updated_at: now,
  },
  {
    id: "edr-impossible-travel",
    title: "Suspicious login after MFA reset",
    description: "User logged in from a new location shortly after MFA reset and password rotation.",
    source: "edr_alert",
    severity: "medium",
    status: "new",
    category: "account_compromise",
    affected_asset: "auth service",
    reporter: "identity-detection",
    confidence: 0.69,
    created_at: now,
    updated_at: now,
  },
];

export const demoDashboard: DashboardSummary = {
  total_findings: demoFindings.length,
  open_findings: 5,
  triage_results: 5,
  high_severity_findings: 3,
  by_severity: [
    { name: "high", count: 2 },
    { name: "medium", count: 2 },
    { name: "critical", count: 1 },
  ],
  by_status: [
    { name: "new", count: 2 },
    { name: "triaged", count: 1 },
    { name: "in_remediation", count: 1 },
    { name: "needs_human_review", count: 1 },
  ],
  by_source: [
    { name: "cisa_kev", count: 1 },
    { name: "bug_bounty", count: 1 },
    { name: "secret_scan", count: 1 },
    { name: "cloud_alert", count: 1 },
    { name: "edr_alert", count: 1 },
  ],
  by_category: [
    { name: "exposed_secret", count: 1 },
    { name: "idor", count: 1 },
    { name: "supply_chain", count: 1 },
    { name: "cloud_misconfiguration", count: 1 },
    { name: "account_compromise", count: 1 },
  ],
  recent_findings: demoFindings,
};

export const demoKevSummary: KevSummary = {
  total_kev_findings: 1,
  critical: 1,
  high: 0,
  medium: 0,
  low: 0,
  unknown: 0,
  overdue: 1,
  due_soon: 0,
  known_ransomware_use: 1,
  top_due_items: [
    {
      finding_id: "kev-cve-2024-3094",
      title: "CVE-2024-3094 XZ Utils supply-chain backdoor exposure",
      cve: "CVE-2024-3094",
      vendor_project: "XZ Utils",
      product: "liblzma",
      severity: "critical",
      category: "supply_chain",
      kev_due_date: "2026-05-10",
      days_until_due: -5,
      is_overdue: true,
      known_ransomware_use: true,
      priority_reason: "CVE-2024-3094 is overdue and has known ransomware use",
    },
  ],
};

export const demoFindingsResponse: FindingListResponse = {
  items: demoFindings,
  total: demoFindings.length,
  limit: 100,
  offset: 0,
};

export const demoActivity: ActivityTimeline = {
  total: 6,
  limit: 20,
  items: [
    {
      type: "finding_created",
      entity_id: "kev-cve-2024-3094",
      title: "KEV import created CVE-2024-3094",
      severity: "critical",
      category: "supply_chain",
      source: "cisa_kev",
      routing_team: null,
      created_at: now,
    },
    {
      type: "triage_completed",
      entity_id: "secret-github-api-key",
      title: "Secret exposure routed to application security",
      severity: "high",
      category: "exposed_secret",
      source: "secret_scan",
      routing_team: "application-security",
      created_at: now,
    },
    {
      type: "workflow_updated",
      entity_id: "bb-idor-invoices",
      title: "IDOR finding moved to triaged",
      severity: "high",
      category: "idor",
      source: "bug_bounty",
      routing_team: "product-security",
      created_at: now,
    },
  ],
};

export const demoWorkspace: WorkspaceData = {
  dashboard: demoDashboard,
  kevSummary: demoKevSummary,
  findings: demoFindingsResponse,
  activity: demoActivity,
};
